default: &default
  adapter: postgresql
  encoding: unicode
  username: 
  password: 
  pool: 5

development:
  <<: *default
  database: 

test:
  <<: *default
  database: 

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: 

# For SolidCable
cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: 

# For SolidQueue
queue:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: 

# For SolidCache
cache:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: 
