default: &default
  adapter: postgresql
  encoding: unicode
  username: kbpoovanna
  password: kbpassword
  pool: 5

development:
  <<: *default
  database: task_manager_development

test:
  <<: *default
  database: task_manager_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: task_manager_production

# For SolidCable
cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: task_manager_cable

# For SolidQueue
queue:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: task_manager_queue

# For SolidCache
cache:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: task_manager_cache
