version: '3'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kbpoovanna
      POSTGRES_PASSWORD: kbpassword
      POSTGRES_DB: task_manager_production
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://kbpoovanna:kbpassword@db:5432/task_manager_production
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
